### PR TITLE
Navbar improvement

### LINKED ISSUE #6: CHANGE - Make nav bar less cluttered / more usable
When logged in, the nav bar is very cluttered. Need to think of a solution to fix this.

### PR DESCRIPTION
**Pull request by KaneD985**
In this PR, I rearrange and combine the course description search and course history search button on the web page navbar, which improves the usability for the webpage.

Storybook: https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-3/prs/22/storybook/?path=/docs/components-nav-appnavbar--basic-not-logged-in

### CODE REVIEW

**Review by wq12li — APPROVED** [review]
Looks good to me.

**Comment by pconrad** [comment]
Since this is a frontend change, I’d like to ask for screenshots and links to storybook entries before the staff reviews it.  

See: slack link: https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685400785702049

**Comment by KaneD985** [comment]
Gotcha, here are the screenshots before and after
微信截图_20230530132906
微信截图_20230530132816

**Comment by KaneD985** [comment]
Also the link to storybook entry is: https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-3/prs/22/storybook/?path=/docs/components-nav-appnavbar--basic-not-logged-in

**Comment by pconrad** [comment]
> Also the link to storybook entry is: https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-3/prs/22/storybook/?path=/docs/components-nav-appnavbar--basic-not-logged-in

Thanks! next time please just put it in the description.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
